# Generated by Django 5.2.6 on 2025-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('dop', models.DateField()),
                ('car_Type', models.CharField(max_length=10)),
            ],
        ),
    ]
